// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataTransPackage.proto

package net.itfeng.nettytcpdemoclient.protocol;

public final class DataTransPackageOuterClass {
  private DataTransPackageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code net.itfeng.nettytcpdemoclient.protocol.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    /**
     * <code>TEST_DATA_TRANS = 1;</code>
     */
    TEST_DATA_TRANS(1),
    /**
     * <code>TEST_DATA_TRANS_RESULT = 2;</code>
     */
    TEST_DATA_TRANS_RESULT(2),
    /**
     * <code>CLIENT_TIME_DIFF = 3;</code>
     */
    CLIENT_TIME_DIFF(3),
    /**
     * <code>HEARTBEAT_PING = 4;</code>
     */
    HEARTBEAT_PING(4),
    /**
     * <code>HEARTBEAT_PONG = 5;</code>
     */
    HEARTBEAT_PONG(5),
    /**
     * <code>ONLINE_EVENT = 6;</code>
     */
    ONLINE_EVENT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>TEST_DATA_TRANS = 1;</code>
     */
    public static final int TEST_DATA_TRANS_VALUE = 1;
    /**
     * <code>TEST_DATA_TRANS_RESULT = 2;</code>
     */
    public static final int TEST_DATA_TRANS_RESULT_VALUE = 2;
    /**
     * <code>CLIENT_TIME_DIFF = 3;</code>
     */
    public static final int CLIENT_TIME_DIFF_VALUE = 3;
    /**
     * <code>HEARTBEAT_PING = 4;</code>
     */
    public static final int HEARTBEAT_PING_VALUE = 4;
    /**
     * <code>HEARTBEAT_PONG = 5;</code>
     */
    public static final int HEARTBEAT_PONG_VALUE = 5;
    /**
     * <code>ONLINE_EVENT = 6;</code>
     */
    public static final int ONLINE_EVENT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return TEST_DATA_TRANS;
        case 2: return TEST_DATA_TRANS_RESULT;
        case 3: return CLIENT_TIME_DIFF;
        case 4: return HEARTBEAT_PING;
        case 5: return HEARTBEAT_PONG;
        case 6: return ONLINE_EVENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:net.itfeng.nettytcpdemoclient.protocol.DataType)
  }

  public interface DataTransPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.itfeng.nettytcpdemoclient.protocol.DataTransPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     **
     * 消息类型
     * </pre>
     *
     * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <pre>
     **
     * 消息类型
     * </pre>
     *
     * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
     * @return The dataType.
     */
    net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType getDataType();

    /**
     * <pre>
     **
     * 客户端的唯一标识
     * </pre>
     *
     * <code>string clientId = 2;</code>
     * @return The clientId.
     */
    java.lang.String getClientId();
    /**
     * <pre>
     **
     * 客户端的唯一标识
     * </pre>
     *
     * <code>string clientId = 2;</code>
     * @return The bytes for clientId.
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     **
     * 消息体
     * </pre>
     *
     * <code>bytes pbData = 3;</code>
     * @return The pbData.
     */
    com.google.protobuf.ByteString getPbData();
  }
  /**
   * Protobuf type {@code net.itfeng.nettytcpdemoclient.protocol.DataTransPackage}
   */
  public static final class DataTransPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.itfeng.nettytcpdemoclient.protocol.DataTransPackage)
      DataTransPackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataTransPackage.newBuilder() to construct.
    private DataTransPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataTransPackage() {
      dataType_ = 0;
      clientId_ = "";
      pbData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataTransPackage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.class, net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.Builder.class);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     **
     * 消息类型
     * </pre>
     *
     * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     **
     * 消息类型
     * </pre>
     *
     * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType getDataType() {
      @SuppressWarnings("deprecation")
      net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType result = net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.valueOf(dataType_);
      return result == null ? net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.UNRECOGNIZED : result;
    }

    public static final int CLIENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientId_;
    /**
     * <pre>
     **
     * 客户端的唯一标识
     * </pre>
     *
     * <code>string clientId = 2;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     **
     * 客户端的唯一标识
     * </pre>
     *
     * <code>string clientId = 2;</code>
     * @return The bytes for clientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PBDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString pbData_;
    /**
     * <pre>
     **
     * 消息体
     * </pre>
     *
     * <code>bytes pbData = 3;</code>
     * @return The pbData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPbData() {
      return pbData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.DEFAULT.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
      }
      if (!pbData_.isEmpty()) {
        output.writeBytes(3, pbData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
      }
      if (!pbData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, pbData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage)) {
        return super.equals(obj);
      }
      net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage other = (net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getClientId()
          .equals(other.getClientId())) return false;
      if (!getPbData()
          .equals(other.getPbData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + PBDATA_FIELD_NUMBER;
      hash = (53 * hash) + getPbData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.itfeng.nettytcpdemoclient.protocol.DataTransPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.itfeng.nettytcpdemoclient.protocol.DataTransPackage)
        net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.class, net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.Builder.class);
      }

      // Construct using net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        clientId_ = "";

        pbData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor;
      }

      @java.lang.Override
      public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage getDefaultInstanceForType() {
        return net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.getDefaultInstance();
      }

      @java.lang.Override
      public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage build() {
        net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage buildPartial() {
        net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage result = new net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage(this);
        result.dataType_ = dataType_;
        result.clientId_ = clientId_;
        result.pbData_ = pbData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage) {
          return mergeFrom((net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage other) {
        if (other == net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.getPbData() != com.google.protobuf.ByteString.EMPTY) {
          setPbData(other.getPbData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                dataType_ = input.readEnum();

                break;
              } // case 8
              case 18: {
                clientId_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                pbData_ = input.readBytes();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int dataType_ = 0;
      /**
       * <pre>
       **
       * 消息类型
       * </pre>
       *
       * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       **
       * 消息类型
       * </pre>
       *
       * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息类型
       * </pre>
       *
       * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType getDataType() {
        @SuppressWarnings("deprecation")
        net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType result = net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.valueOf(dataType_);
        return result == null ? net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       **
       * 消息类型
       * </pre>
       *
       * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息类型
       * </pre>
       *
       * <code>.net.itfeng.nettytcpdemoclient.protocol.DataType dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <pre>
       **
       * 客户端的唯一标识
       * </pre>
       *
       * <code>string clientId = 2;</code>
       * @return The clientId.
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       **
       * 客户端的唯一标识
       * </pre>
       *
       * <code>string clientId = 2;</code>
       * @return The bytes for clientId.
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       **
       * 客户端的唯一标识
       * </pre>
       *
       * <code>string clientId = 2;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 客户端的唯一标识
       * </pre>
       *
       * <code>string clientId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 客户端的唯一标识
       * </pre>
       *
       * <code>string clientId = 2;</code>
       * @param value The bytes for clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pbData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       **
       * 消息体
       * </pre>
       *
       * <code>bytes pbData = 3;</code>
       * @return The pbData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPbData() {
        return pbData_;
      }
      /**
       * <pre>
       **
       * 消息体
       * </pre>
       *
       * <code>bytes pbData = 3;</code>
       * @param value The pbData to set.
       * @return This builder for chaining.
       */
      public Builder setPbData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pbData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       **
       * 消息体
       * </pre>
       *
       * <code>bytes pbData = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPbData() {
        
        pbData_ = getDefaultInstance().getPbData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:net.itfeng.nettytcpdemoclient.protocol.DataTransPackage)
    }

    // @@protoc_insertion_point(class_scope:net.itfeng.nettytcpdemoclient.protocol.DataTransPackage)
    private static final net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage();
    }

    public static net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataTransPackage>
        PARSER = new com.google.protobuf.AbstractParser<DataTransPackage>() {
      @java.lang.Override
      public DataTransPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataTransPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataTransPackage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public net.itfeng.nettytcpdemoclient.protocol.DataTransPackageOuterClass.DataTransPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026DataTransPackage.proto\022&net.itfeng.net" +
      "tytcpdemoclient.protocol\"x\n\020DataTransPac" +
      "kage\022B\n\010dataType\030\001 \001(\01620.net.itfeng.nett" +
      "ytcpdemoclient.protocol.DataType\022\020\n\010clie" +
      "ntId\030\002 \001(\t\022\016\n\006pbData\030\003 \001(\014*\230\001\n\010DataType\022" +
      "\013\n\007DEFAULT\020\000\022\023\n\017TEST_DATA_TRANS\020\001\022\032\n\026TES" +
      "T_DATA_TRANS_RESULT\020\002\022\024\n\020CLIENT_TIME_DIF" +
      "F\020\003\022\022\n\016HEARTBEAT_PING\020\004\022\022\n\016HEARTBEAT_PON" +
      "G\020\005\022\020\n\014ONLINE_EVENT\020\006B(\n&net.itfeng.nett" +
      "ytcpdemoclient.protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_itfeng_nettytcpdemoclient_protocol_DataTransPackage_descriptor,
        new java.lang.String[] { "DataType", "ClientId", "PbData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
